spring.datasource.url=jdbc:mysql://localhost:3306/neuralshift
spring.datasource.username=neuralshift
spring.datasource.password=neuralshift
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true